// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnQFlbWZlZu8ggW5mG5ahBuf2vT2ufZkU',
    appId: '1:776250129202:web:25b4d7bfc9d2fab387752b',
    messagingSenderId: '776250129202',
    projectId: 'chatapp-daefb',
    authDomain: 'chatapp-daefb.firebaseapp.com',
    storageBucket: 'chatapp-daefb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqD-7Wg_lR5zsrNhbXXhWFkaAcN2cKxc',
    appId: '1:776250129202:android:e8d0f2a323ab5c7887752b',
    messagingSenderId: '776250129202',
    projectId: 'chatapp-daefb',
    storageBucket: 'chatapp-daefb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppVEss_JF9pOzMnPbY0KS2ka-1TBK_C8',
    appId: '1:776250129202:ios:b1064059826c021e87752b',
    messagingSenderId: '776250129202',
    projectId: 'chatapp-daefb',
    storageBucket: 'chatapp-daefb.appspot.com',
    iosClientId: '776250129202-9b66q0n99edvii5asj815j1b3h3g0rf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
